version: '3.7'

services:
  street-cleaning:
    image: "docwhat/street_cleaning"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "4"
    deploy:
      labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathStripRegex:/street-cleaning{?:.ics|}"
      - "traefik.port=80"
      - "traefik.backend=street-cleaning"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.SSLForceHost=false"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2

  work:
    image: "docwhat/work-calendar"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "4"
    deploy:
      labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathPrefixStripRegex:/${WORK_CALENDAR_SECRET_VALUE}{?:.ics|}"
      - "traefik.port=80"
      - "traefik.backend=work-calendar"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2

networks:
  traefik-public:
    external: true
