version: '3.7'

x-common:
  logging:
    &default-logging
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"

services:
  street-cleaning:
    image: "docwhat/street_cleaning"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging: *default-logging
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathStripRegex:/street-cleaning{?:.ics|}"
      - "traefik.port=80"
      - "traefik.backend=street-cleaning"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.SSLForceHost=false"
      resources:
        limits:
          memory: "16M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2
      placement:
        constraints:
          - "node.role==worker"

  work:
    image: "docwhat/work-calendar"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging: *default-logging
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathPrefixStripRegex:/${WORK_CALENDAR_SECRET_VALUE}{?:.ics|}"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.port=80"
      - "traefik.backend=work-calendar"
      resources:
        limits:
          memory: "16M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - "node.role==worker"

networks:
  traefik-public:
    external: true
