version: '3.7'

services:
  blog:
    image: "docwhat/docwhat:master"
    read_only: true
    volumes:
    - type: "tmpfs"
      target: "/var/cache/nginx"
    - type: "tmpfs"
      target: "/run"
    networks:
      - "traefik-public"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    deploy:
      labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:next.docwhat.org"
      - "traefik.port=80"
      - "traefik.backend=docwhat-next"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.priority=10"
      resources:
        limits:
          memory: "32M"
        reservations:
          memory: "8M"
      restart_policy:
        delay: "2s"
      replicas: 2
      rollback_config:
        parallelism: 2
      update_config:
        parallelism: 1

networks:
  traefik-public:
    external: true
