version: '3.7'

x-common:
  logging:
    &default-logging
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"

services:
  blog:
    image: "docwhat/docwhat:live"
    read_only: true
    volumes:
    - type: "tmpfs"
      target: "/var/cache/nginx"
    - type: "tmpfs"
      target: "/run"
    networks:
      - "traefik-public"
    logging: *default-logging
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org,www.docwhat.org"
      - "traefik.port=80"
      - "traefik.backend=docwhat-prod"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.priority=10"
      resources:
        limits:
          memory: "64M"
      restart_policy:
        delay: "2s"
      replicas: 3
      rollback_config:
        parallelism: 2
      update_config:
        parallelism: 2
        failure_action: rollback
      placement:
        constraints:
          - "node.role==worker"

networks:
  traefik-public:
    external: true
