version: '3.7'

x-common:
  logging:
    &default-logging
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"

services:

  # Redirect "go get" for docwhat.org
  go-importd:
    image: "docwhat/go-importd"
    read_only: true
    networks:
      - traefik-public
    logging: *default-logging
    environment:
      - "GO_IMPORTD_GITHUB_USER_URL=https://github.com/docwhat"
      - "GO_IMPORTD_IMPORT_DOMAIN=docwhat.org"
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;Query:go-get=1"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.port=80"
      - "traefik.backend=go-importd"
      resources:
        limits:
          memory: "8M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - "node.role==worker"

networks:
  traefik-public:
    external: true
