version: "3.7"

x-common:
  logging:
    &default-logging
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"

services:
  app:
    image: "swarmpit/swarmpit"
    environment:
      - "SWARMPIT_DB=http://db:5984"
      - "SWARMPIT_INFLUXDB=http://influxdb:8086"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefik-public"
      - "net"
    logging: *default-logging
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:swarmpit.gerf.net"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.port=8080"
      - "traefik.backend=swarmpit"
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: "300M"

  db:
    image: "couchdb:2.3"
    volumes:
      - "data:/opt/couchdb/data"
    networks:
      - "net"
    logging: *default-logging
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=false"
      placement:
        constraints:
          - "node.labels.swarmpit.swarmpit-data == true"
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: "64M"

  influxdb:
    image: "influxdb:1.7"
    volumes:
      - "logs:/var/lib/influxdb"
    networks:
      - "net"
    logging: *default-logging
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.labels.swarmpit.swarmpit-logs==true"
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: "200M"

  agent:
    image: "swarmpit/agent"
    environment:
      - "DOCKER_API_VERSION=1.39"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "net"
    logging: *default-logging
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=false"
        - "swarmpit.agent=true"
      mode: "global"
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: "20M"

networks:
  net:
    attachable: true
  traefik-public:
    external: true

volumes:
  data:
    name: "swarmpit-data"
  logs:
    name: "swarmpit-logs"
