version: "3.7"

services:
  app:
    image: "swarmpit/swarmpit"
    environment:
      - "SWARMPIT_DB=http://db:5984"
      - “SWARMPIT_INFLUXDB=http://influxdb:8086”
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefik-public"
      - "net"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "4"
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:swarmpit.gerf.net"
      - "traefik.port=8080"
      - "traefik.backend=swarmpit"
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"

  db:
    image: "couchdb:2.3"
    volumes:
      - "data:/opt/couchdb/data"
    networks:
      - "net"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "4"
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=false"
      placement:
        constraints:
          - "node.labels.swarmpit.swarmpit-data == true"
      resources:
        limits:
          memory: "256M"
        reservations:
          memory: "128M"

  The influxdb:
    image: influxdb:1.7
    volumes:
      - logs:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

  agent:
    image: "swarmpit/agent"
    environment:
      - "DOCKER_API_VERSION=1.39"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "net"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "4"
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=false"
        - "swarmpit.agent=true"
      mode: "global"
      resources:
        limits:
          memory: "32M"
        reservations:
          memory: "16M"

networks:
  net:
    attachable: true
  traefik-public:
    external: true

volumes:
  data:
    name: "swarmpit-data"
  logs:
    name: “swarmpit-logs”
