version: '3.7'

services:
  traefik:
    image: "traefik:maroilles"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    read_only: true
    configs:
      - source: "rules"
        target: "/rules.toml"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "traefik-data:/data:rw"
      - type: tmpfs
        target: "/tmp"
    command:
      - "--debug=false"
      - "--logLevel=WARNING"
      # logLevel values "ERROR" "WARNING" "INFO" "DEBUG"
      - "--defaultEntryPoints=https,http"
      - "--sendAnonymousUsage"

      - "--api"
      - "--api.entryPoint=traefik"
      - "--api.dashboard"
      - "--api.statistics.recentErrors=30"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"

      - "--docker"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.domain=docwhat.org"
      - "--docker.swarmMode"
      - "--docker.watch"
      - "--docker.exposedByDefault=false"

      - "--acme"
      - "--acme.email=docwhat@gmail.com"
      - "--acme.storage=/data/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onHostRule"
      - "--acme.acmeLogging"
      - "--acme.tlsChallenge"

      - "--retry"

      - "--file"
      - "--file.filename=/rules.toml"
      - "--file.watch"

    secrets:
      - "htpasswd"

    deploy:
      labels:
        - "com.ouroboros.enable=true"
        - "traefik.enable=true"
        - "traefik.tags=traefik-public"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:docwhat.org;PathPrefixStrip:/traefik/"
        - "traefik.frontend.auth.basic.usersFile=/run/secrets/htpasswd"
        - "traefik.port=8080"
        - "traefik.backend=traefik"

      placement:
        constraints:
        - node.role == manager
        # preferences:
        # - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
      update_config:
        failure_action: rollback
      replicas: 1

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  traefik-data:
    name: "traefik-data"

configs:
  rules:
    file: "configs/traefik-rules.toml"

secrets:
  htpasswd:
    file: "secrets/htpasswd"
    name: "traefik_htpasswd_${HTPASSWD_SUM}"
