version: '3.7'

x-common:
  logging:
    &default-logging
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"

services:
  db:
    image: "mongo:4.0"
    read_only: true
    configs:
      - source: "db_config"
        target: "/docker-entrypoint-initdb.d/mongoconfig.js"
    secrets:
      - "db_username"
      - "db_password"
    environment:
      - "MONGO_INITDB_DATABASE=xbs"
      - "MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_username"
      - "MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_password"
    networks:
      - "default"
    logging: *default-logging
    volumes:
      - type: "tmpfs"
        target: "/tmp"
      - type: "tmpfs"
        target: "/run"
      - type: "volume"
        source: "xbs-db-data"
        target: "/data/db"
      - type: "volume"
        source: "xbs-configdb-data"
        target: "/data/configdb"
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.labels.xbrowsersync.db-data == true"
      resources:
        limits:
          memory: "64M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      update_config:
        failure_action: rollback

  api:
    image: "xbrowsersync/api:1.1.8"
    depends_on:
      - "db"
    networks:
      - "default"
      - "traefik-public"
    logging: *default-logging
    secrets:
      - source: "settings"
        target: "/usr/src/api/config/settings.json"
    read_only: true
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=true"
        - "traefik.tags=traefik-public"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:xbrowsersync.gerf.net"
        - "traefik.port=8080"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.backend=xbs-api"
      replicas: 2
      resources:
        limits:
          memory: "64M"
        reservations:
          memory: "20M"
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - "node.role==worker"

volumes:
  xbs-db-data:
    name: "xbs-db-data"
  xbs-configdb-data:
    name: "xbs-configdb-data"

configs:
  db_config:
    file: "configs/xbs_db_config.js"
    name: "xbrowsersync-${XBS_DB_CONFIG_JS_SUM}"

secrets:
  db_username:
    file: secrets/xbs_db_username.txt
    name: "xbs_db_username-${XBS_DB_USERNAME_TXT_SUM}"
  db_password:
    file: secrets/xbs_db_password.txt
    name: "xbs_db_password-${XBS_DB_PASSWORD_TXT_SUM}"
  settings:
    file: secrets/xbs_settings.json
    name: "xbs_settings-${XBS_SETTINGS_JSON_SUM}"

networks:
  default:
  traefik-public:
    external: true
