apiVersion: v1
kind: Service
metadata:
  name: static-site-service
  # https://www.linode.com/docs/kubernetes/deploy-nodebalancers-with-linode-ccm/#annotations
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-protocol: "tcp"
  labels:
    app: static-site
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: static-site
  sessionAffinity: None
