version: '3.7'

### INCLUDE BEGIN


x-twelve-factor-app:
  read_only: true
  logging:
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"
  deploy:
    labels:
    - "swarmpit.service.deployment.autoredeploy=true"
    restart_policy:
      delay: "2s"
    replicas: 2
    rollback_config:
      parallelism: 1
      delay: "1s"
    update_config:
      parallelism: 1
      delay: "10s"
      failure_action: "rollback"
    placement:
      constraints:
        - "node.role==worker"


x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "2"
  driver: "json-file"

x-twelve-deploy:
  &twelve-deploy
  labels:
  - "swarmpit.service.deployment.autoredeploy=true"
  restart_policy:
    delay: "2s"
  replicas: 2
  rollback_config:
    parallelism: 1
    delay: "1s"
  update_config:
    parallelism: 1
    delay: "10s"
    failure_action: "rollback"
  placement:
    constraints:
      - "node.role==worker"


### INCLUDE FINISH

services:
  calendar-street-cleaning:
    image: "docker.io/docwhat/street_cleaning:latest"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging: *default-logging
    deploy:
      <<: *twelve-deploy
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathStripRegex:/street-cleaning{?:.ics|}"
      - "traefik.port=80"
      - "traefik.backend=street-cleaning"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.SSLForceHost=false"
      resources:
        limits:
          memory: "16M"
      replicas: 2

  calendar-work:
    image: "docker.io/docwhat/work-calendar:latest"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    networks:
      - traefik-public
    logging: *default-logging
    deploy:
      <<: *twelve-deploy
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:docwhat.org;Method:GET,HEAD;PathPrefixStripRegex:/${WORK_CALENDAR_SECRET_VALUE}{?:.ics|}"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.port=80"
      - "traefik.backend=work-calendar"
      resources:
        limits:
          memory: "16M"
      replicas: 2

networks:
  traefik-public:
    external: true
