version: '3.7'

### INCLUDE BEGIN

x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "2"
  driver: "json-file"


x-twelve-deploy:
  &twelve-deploy
  labels:
  - "swarmpit.service.deployment.autoredeploy=true"
  restart_policy:
    delay: "2s"
  replicas: 2
  rollback_config:
    parallelism: 1
    delay: "1s"
  update_config:
    parallelism: 1
    delay: "10s"
    failure_action: "rollback"
  placement:
    constraints:
      - "node.role==worker"


### INCLUDE FINISH

services:
  next-blog:
    image: "docker.io/docwhat/docwhat:master"
    read_only: true
    volumes:
    - type: "tmpfs"
      target: "/var/cache/nginx"
    - type: "tmpfs"
      target: "/run"
    networks:
      - "traefik-public"
    logging: *default-logging
    deploy:
      <<: *twelve-deploy
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:next.docwhat.org"
      - "traefik.port=80"
      - "traefik.backend=docwhat-next"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.priority=10"
      resources:
        limits:
          memory: "32M"
      replicas: 3

networks:
  traefik-public:
    external: true
