version: '3.7'

### INCLUDE BEGIN


x-twelve-factor-app:
  read_only: true
  logging:
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"
  deploy:
    labels:
    - "swarmpit.service.deployment.autoredeploy=true"
    restart_policy:
      delay: "2s"
    replicas: 2
    rollback_config:
      parallelism: 1
      delay: "1s"
    update_config:
      parallelism: 1
      delay: "10s"
      failure_action: "rollback"
    placement:
      constraints:
        - "node.role==worker"


x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "2"
  driver: "json-file"

x-twelve-deploy:
  &twelve-deploy
  labels:
  - "swarmpit.service.deployment.autoredeploy=true"
  restart_policy:
    delay: "2s"
  replicas: 2
  rollback_config:
    parallelism: 1
    delay: "1s"
  update_config:
    parallelism: 1
    delay: "10s"
    failure_action: "rollback"
  placement:
    constraints:
      - "node.role==worker"


### INCLUDE FINISH

services:

  letsencrypt:
    image: "docker.io/nginx:stable-alpine"
    read_only: true
    volumes:
    - type: tmpfs
      target: "/var/cache/nginx"
    - type: tmpfs
      target: "/run"
    - type: "bind"
      source: "/var/letsencrypt/"
      target: "/usr/share/nginx/html/"
      # readonly: true
    networks:
      - traefik-public
    logging: *default-logging
    healthcheck:
      interval: 1m
      timeout: 10s
      retries: 5
      test:
      - "CMD"
      - "wget"
      - "http://localhost/.well-known/confirm"
      - "-q"
      - "-O-"
    deploy:
      labels:
      - "swarmpit.service.deployment.autoredeploy=true"
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:gerf.org;PathPrefix:/.well-known/"
      - "traefik.backend=letsencrypt"
      - "traefik.frontend.headers.SSLForceHost=false"
      resources:
        limits:
          memory: "16M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      replicas: 2
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - "node.role == manager"
          - "node.labels.letsencrypt.well-known-mount == true"

networks:
  traefik-public:
    external: true
