version: "3.7"

{{file.Read "include/x-common.yaml"}}

services:
  portainer-agent:
    image: "portainer/agent"
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - "agent-network"
    logging: *default-logging
    deploy:
      mode: "global"
      resources:
        limits:
          memory: "16M"
      placement:
        constraints:
          - "node.platform.os == linux"

  portainer:
    image: "portainer/portainer:1.22.0"
    command:
      - "--host=tcp://tasks.portainer-agent:9001"
      - "--tlsskipverify"
    networks:
      - "agent-network"
      - "traefik-public"
    volumes:
      - "portainer-data:/data:rw"
    logging: *default-logging
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.frontend.rule=Host:portainer.gerf.net"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
      replicas: 1
      resources:
        limits:
          memory: "50M"
      update_config:
        failure_action: "rollback"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      placement:
        constraints:
          - "node.role == manager"
          - "node.labels.portainer.portainer-data == true"

networks:
  agent-network:
    attachable: true
  traefik-public:
    external: true

volumes:
  portainer-data:
    name: "portainer-data"
