version: '3.7'

### INCLUDE BEGIN


x-twelve-factor-app:
  read_only: true
  logging:
    options:
      max-size: "200k"
      max-file: "2"
    driver: "json-file"
  deploy:
    labels:
    - "swarmpit.service.deployment.autoredeploy=true"
    restart_policy:
      delay: "2s"
    replicas: 2
    rollback_config:
      parallelism: 1
      delay: "1s"
    update_config:
      parallelism: 1
      delay: "10s"
      failure_action: "rollback"
    placement:
      constraints:
        - "node.role==worker"


x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "2"
  driver: "json-file"

x-twelve-deploy:
  &twelve-deploy
  labels:
  - "swarmpit.service.deployment.autoredeploy=true"
  restart_policy:
    delay: "2s"
  replicas: 2
  rollback_config:
    parallelism: 1
    delay: "1s"
  update_config:
    parallelism: 1
    delay: "10s"
    failure_action: "rollback"
  placement:
    constraints:
      - "node.role==worker"


### INCLUDE FINISH

services:
  mongodb:
    image: "docker.io/mongo:4.0"
    read_only: true
    configs:
      - source: "db_config"
        target: "/docker-entrypoint-initdb.d/mongoconfig.js"
    secrets:
      - "db_username"
      - "db_password"
    environment:
      - "MONGO_INITDB_DATABASE=xbs"
      - "MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_username"
      - "MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_password"
    networks:
      - "default"
    logging: *default-logging
    volumes:
      - type: "tmpfs"
        target: "/tmp"
      - type: "tmpfs"
        target: "/run"
      - type: "volume"
        source: "xbs-db-data"
        target: "/data/db"
      - type: "volume"
        source: "xbs-configdb-data"
        target: "/data/configdb"
    deploy:
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.labels.xbrowsersync.db-data == true"
      resources:
        limits:
          memory: "100M"
      restart_policy:
        condition: "on-failure"
        delay: "2s"
      update_config:
        failure_action: rollback

  xbrowsersync-api:
    # image: "docker.io/xbrowsersync/api:1.1.10"
    image: "docker.io/docwhat/xbrowsersync-api:1.1.10-healthcheck"
    depends_on:
      - "mongodb"
    networks:
      - "default"
      - "traefik-public"
    logging: *default-logging
    secrets:
      - source: "settings"
        target: "/usr/src/api/config/settings.json"
    read_only: true
    deploy:
      <<: *twelve-deploy
      labels:
        - "swarmpit.service.deployment.autoredeploy=true"
        - "traefik.enable=true"
        - "traefik.tags=traefik-public"
        - "traefik.docker.network=traefik-public"
        - "traefik.frontend.rule=Host:xbrowsersync.gerf.net"
        - "traefik.port=8080"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.backend=xbs-api"
      resources:
        limits:
          memory: "64M"

volumes:
  xbs-db-data:
    name: "xbs-db-data"
  xbs-configdb-data:
    name: "xbs-configdb-data"

configs:
  db_config:
    file: "configs/xbs_db_config.js"
    name: "xbrowsersync-${XBS_DB_CONFIG_JS_SUM}"

secrets:
  db_username:
    file: secrets/xbs_db_username.txt
    name: "xbs_db_username-${XBS_DB_USERNAME_TXT_SUM}"
  db_password:
    file: secrets/xbs_db_password.txt
    name: "xbs_db_password-${XBS_DB_PASSWORD_TXT_SUM}"
  settings:
    file: secrets/xbs_settings.json
    name: "xbs_settings-${XBS_SETTINGS_JSON_SUM}"

networks:
  default:
  traefik-public:
    external: true
