apiVersion: v1
kind: Service
metadata:
  name: docwhat-org-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: docwhat-org
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: docwhat-blog
  sessionAffinity: None
